version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.4
    working_directory: ~/repo
    environment:
      MY_ENV: aaa
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            - v1-dependencies-
      - run:
          command: pip install wheel
      - run:
          command: python setup bdist_wheel
  lint:
    docker:
      - image: circleci/python:3.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: pip install flake8
      - run:
          command: flake8
  type-check:
    docker:
      - image: circleci/python:3.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: pip install mypy
      - run:
          command: mypy --ignore-missing-imports
  format:
    docker:
      - image: circleci/python:3.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: pip install black
      - run:
          command: black
  test:
    docker:
      - image: circleci/python:3.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: pip install pytest pytest-cov
      - run:
          command: pytest -v --cov
  deploy:
    docker:
      - image: circleci/python:3.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: pip install twine
      - run:
          command: twine upload dist/*
workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - lint
      - type-check
      - format
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
